# CI that:
#
# * checks the code is formatted correctly
# * checks the code builds correctly
# * checks the code has no clippy lints

name: Check

on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add tools
        run: sudo apt-get update -y && sudo apt-get install -y graphviz
      - name: Format
        run: cargo fmt --check
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Build with 1.74
        run: |
          cargo clean
          rustup update 1.74 --no-self-update
          cargo +1.74 build
