# CI that:
#
# * checks the code is formatted correctly
# * checks the code builds correctly
# * checks the code has no clippy lints

name: Check

on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings" 

jobs:
  do_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: cargo fmt --check
      - name: Build
        run: cargo build
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Build with 1.67.1
        run: |
          cargo clean
          rustup update 1.67.1 --no-self-update
          cargo +1.67.1 build
