# CI that:
#
# * reports the licenses of all dependencies

name: Licenses

on: [push, pull_request]

jobs:
  print_licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-license
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-license
          version: "^0.5"
      - name: Print Licences
        run: cargo license
